version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
